language: android
android:
    components:
        - tools
        - build-tools-23.0.1
        - platform-tools-23.0.1
        - android-23

before_install:
    - export TERM=dumb
    - pip install codecov

script:
    bash gradlew clean build --debug

notifications:
    email: false

after_success:
    - codecov