language: android
android:
    components:
        - tools
        - build-tools-23.0.1
        - platform-tools-23.0.1
        - android-23

before_install:
    - export TERM=dumb

install:
    bash gradlew build

script:
    bash gradlew clean assembleDebug test --debug

notifications:
    email: false