language: android
android:
    components:
        - build-tools-23.0.1
        - platform-tools-23.0.1
        - android-23

before_install:
    - export TERM=dumb

script:
    bash gradlew clean build

notifications:
    email: false