language: android
android:
    components:
        - platform-tools-23.0.1
        - android-23
        - tools

before_install:
    - export TERM=dumb

script:
    bash gradlew clean build

notifications:
    email: false