sudo: true

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron
      language: android
      jdk:
        - oraclejdk8

      android:
        components:
          - tools
          - build-tools-27.0.3
          - platform-tools
          - android-23
          - extra-android-support

      before_install:
        - export TERM=dumb
        - pip install --user codecov

      script:
        bash gradlew test jacocoTestReport

      notifications:
        email: false

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: Tests
      name: Dead link check
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron

      before_script:
        - npm run doc-prepare
        - npm run --prefix doc/framework clone-repos
        - gem install typhoeus
      script:
        - HYDRA_MAX_CONCURRENCY=20 npm run --prefix doc/framework dead-links
